### ISSUE TITLE
Web Dashboard

### ISSUE THREAD

**Issue by aklinker1** [aklinker1/miasma#20]
- [x] ~~_View apps_~~ #25 
- [x] ~~Start/stop apps_~~ #25 
- [x] ~~_Open app URL_~~ #32 
- [x] ~~_Create App_~~ c7bfadf6b65a4eed920babe782dfac0fd06191e1
- [x] ~~_Delete App_~~ #46
- [x] ~~_Restart App_~~ #46
- [x] ~~_View app details_~~ #46
- [x] ~~_Edit app details_~~ #46
- [x] ~~_View `docker service logs`_~~ #64 
- [x] ~~_View `docker service ps`_~~ #62 
- [ ] Enable/disable plugins
- [x] ~~_View service distribution across the cluster_~~ #29 
- [x] ~~_Add node help_~~ #45 
- [x] Edit node labels
