### ISSUE TITLE
Imporve Usage Docs

### ISSUE THREAD

**Issue by aklinker1** [aklinker1/miasma#33]
- [x] ~~_Configuring DNS records (local network and public internet)_~~ #33 
- [x] ~~_Configuring SSL for Traefik plugin (if there's any additional steps)_~~ #39 
- [x] ~~_Intra-app communication_~~ #33

**Comment by prologic** [comment]
Actually I _think_ this has less to do with any "Cloud" provider and more to do with just general instructions.

For example, I'd like to run this up in my on-prem private cloud if you will 😅 -- I have a small 22 RU Rack cabinet with 3x 1RU Hypervisor nodes running Proxmox VE.

If we can keep your project miasma "cloud agnostic" it'll be generally useful in more places (not just cloud) 👌

**Comment by aklinker1** [comment]
Most of that already exists, I just need to add more docs around the things listed in the issue. Though you're correct, it's less cloud docs and more generic docs.

Let me ask you this. You want to run Miasma on your local network, when you go to the documentation, what do you want to know and in what order?

For example, I had the same use case as you, running apps on my local network, I wrote the docs in order of what I would have wanted to know:

1. Does this do what I need it to do?
2. How do I install it?
3. How do I add nodes?
4. How do I create apps?
5. What about routing and DNS for my local network?

What you want to know is probable different than myself, and I'm probably missing steps since I wrote everything myself and don't really need the docs.

**Comment by aklinker1** [comment]
I'm very bad at writing in general, so that usually doesn't translate well to large documentation websites. So if you have any recommendations on structure or content, LMK.

**Comment by prologic** [comment]
I'm pretty bad at docs too 😅 But the list above is a great start!

My general rule of thumb is simple:

> If I can't figure out and install something by reading it's README within ~5m you've lost me :D
